//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpeggiatorLib {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RpeggiatorLib.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The engine has not been properly initialized..
        /// </summary>
        internal static string EngineNotInitializedExceptionMessage {
            get {
                return ResourceManager.GetString("EngineNotInitializedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The method can&apos;t find a position which avoid every structures..
        /// </summary>
        internal static string InfiniteOverlapCheckExceptionMessage {
            get {
                return ResourceManager.GetString("InfiniteOverlapCheckExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified dimension is invalid..
        /// </summary>
        internal static string InvalidDimensionForInsertionExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidDimensionForInsertionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The inventory slot id is invalid..
        /// </summary>
        internal static string InvalidInventorySlotIdExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidInventorySlotIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The coordinates of at least one step is invalid..
        /// </summary>
        internal static string InvalidPathStepCoordinatesExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidPathStepCoordinatesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The coordinates of the player relative to the door are invalid..
        /// </summary>
        internal static string InvalidPlayerThroughDoorCoordinatesExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidPlayerThroughDoorCoordinatesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified render image file is invalid..
        /// </summary>
        internal static string InvalidRenderExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidRenderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified resources path is invalid..
        /// </summary>
        internal static string InvalidResourcesPathExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidResourcesPathExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified identifier does not exist in the database..
        /// </summary>
        internal static string InvalidSpriteIdExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidSpriteIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database connection has failed. Details : {0}. Stacktrace : {1}.
        /// </summary>
        internal static string InvalidSqliteConnectionExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidSqliteConnectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This parameter should be greater than zero..
        /// </summary>
        internal static string LowerOrEqualZeroExceptionMessage {
            get {
                return ResourceManager.GetString("LowerOrEqualZeroExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to resolve this quadratic equation..
        /// </summary>
        internal static string NoQuadraticSolutionExceptionMessage {
            get {
                return ResourceManager.GetString("NoQuadraticSolutionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This sub-type of render has not been implemented..
        /// </summary>
        internal static string NotImplementedRenderExceptionMessage {
            get {
                return ResourceManager.GetString("NotImplementedRenderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This virtual method ou property has not been implemented..
        /// </summary>
        internal static string NotImplementedVirtualExceptionMessage {
            get {
                return ResourceManager.GetString("NotImplementedVirtualExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Z-index property for this subtype has not been implemented..
        /// </summary>
        internal static string NotImplementedZindexTypeExceptionMessage {
            get {
                return ResourceManager.GetString("NotImplementedZindexTypeExceptionMessage", resourceCulture);
            }
        }
    }
}
